name: Go-CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Run Scripts
      run: cd DS && for i in $(ls -al | cut -d' ' -f10 | cut -d'/' -f2); do go run $i; done
